version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    reviewers:
      - 'leonardoalemax'
    assignees:
      - 'leonardoalemax'
    commit-message:
      prefix: 'chore'
